name: 🏭 Cut Mod Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Semver Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  cut_release:
    name: "Cut Release"
    uses: open-goal/mod-bundling-tools/.github/workflows/mod-bundler.yml@v1
    with:
      semverBump: ${{ inputs.bump }}
      metadataName: "Random Cell Order"
      metadataDescription: "Jak 1 but you must pick up cells in the (random) specified order. Check the website for more info on toggle-able settings."
      metadataSupportedGames: "jak1"
      metadataAuthors: "barg,SixRock,Dexz"
      metadataTags: "speedrunning,challenge,gameplay-mod,rng"
      metadataWebsiteUrl: "https://github.com/OpenGOAL-Mods/OG-RCO/blob/main/README.md"
      toolingRepo: "OpenGOAL-Mods/OG-Mod-Base"
      gameAssetsDir: "game/assets"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
